$
$ IBM VisualAge C++ Professional, Version 4.0
$
$ Licensed Materials - Property of IBM
$
$ (C) Copyright IBM Corp. 1998. All Rights Reserved.
$
$ The following [enclosed] code is sample code created by IBM
$ Corporation.  This sample code is not part of any standard IBM product
$ and is provided to you solely for the purpose of assisting you in the
$ development of your applications.  The code is provided 'AS IS',
$ without warranty of any kind.  IBM shall not be liable for any damages
$ arising out of your use of the sample code, even if they have been
$ advised of the possibility of such damages.
$

$set SET_1 This is set #1
aMSG_1 This is message #1 in set #1
aMSG_2 This is message #2 in set #1

$set SET_2 This is set #2
bMSG_1 This is message #1 in set #2
bMSG_2 This is message #2 in set #2
